config/routes.rb
Rails.application.routes.draw do

  post 'film/search', to:'films#search', as: 'search'

  root 'films#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def set_config
    @configuration = Tmdb::Configuration.new
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  def index
  end

  def search
    @film = SearchFilm.new(params[:film_title]).perform
  end

  def show
    @film = Tmdb::Movie.detail(params[:id])
  	@images = Tmdb::Movie.images(params[:id])
  	@cast = Tmdb::Movie.casts(params[:id])
  	@trailers = Tmdb::Movie.trailers(params[:id])
  	@similar_movies = Tmdb::Movie.similar_movies(params[:id])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @film = Tmdb::Movie.find(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/films/index.html.erb
<h1>Search Film</h1>

<%= form_tag(search_path) do %>
  <%= text_field_tag('film_title', nil) %>

<% end %>

app/views/films/search.html.erb
<h1>Search Result</h1>
	<%= @film %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/index.html.erb
<h1>Searches#index</h1>
<p>Find me in app/views/searches/index.html.erb</p>